apiVersion: batch/v1
kind: Job
metadata:
  name: validate
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
        - name: validate
          image: alpine
          command:
            - "bin/sh"
      restartPolicy: Never
  backoffLimit: 2
